# Sample configuration for Homely MQTT Add-on
# Copy this to your Home Assistant configuration.yaml or use the add-on UI

# Add-on configuration
homely_mqtt:
  mqtt_broker_host: "192.168.1.100"  # Your MQTT broker IP address
  mqtt_broker_port: 1883              # MQTT broker port (usually 1883)
  mqtt_username: "your_username"      # MQTT broker username (optional)
  mqtt_password: "your_password"      # MQTT broker password (optional)
  mqtt_client_id: "homely_mqtt"       # Unique client ID
  mqtt_topic_prefix: "homely"         # Topic prefix for all messages
  log_level: "info"                   # Log level: debug, info, warn, error
  auto_discovery: true                # Enable Home Assistant MQTT discovery
  discovery_prefix: "homeassistant"   # MQTT discovery prefix

# Alternative: Minimal configuration
# homely_mqtt:
#   mqtt_broker_host: "localhost"
#   mqtt_broker_port: 1883

# Note: If you're using the add-on UI in Home Assistant,
# you can configure these options through the add-on configuration panel
# instead of editing this file manually.